// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DataAccessObjects;

#nullable disable

namespace DataAccessObjects.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("tblRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "10b3358d-e289-461d-976a-6efdc4968299",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "85307162-d0a5-4613-9d54-543085183ed9",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "ca98ee5e-8158-442e-8ddd-89f7fd988b31",
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("tblRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("tblUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("tblUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("tblUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("tblUserTokens", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PasswordHash");

                    b.HasIndex("RefreshToken");

                    b.HasIndex("UserName");

                    b.ToTable("tblUsers", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.Models.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("tblAttachments");
                });

            modelBuilder.Entity("BusinessObjects.Models.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreaterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReplyToId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("CreaterId");

                    b.HasIndex("PostId");

                    b.HasIndex("ReplyToId");

                    b.ToTable("tblComments");
                });

            modelBuilder.Entity("BusinessObjects.Models.Entities.Feed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreaterId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreaterId");

                    b.ToTable("tblFeeds");
                });

            modelBuilder.Entity("BusinessObjects.Models.Entities.Major", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsDeleted")
                        .HasMaxLength(50)
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("tblMajors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("058006cb-ea6e-4b78-a9cc-f41aed7b971c"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A major of FPT University",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 7, 9, 0, 14, 29, 625, DateTimeKind.Local).AddTicks(7645),
                            Name = "Software Engineering"
                        },
                        new
                        {
                            Id = new Guid("c0a29af4-b397-4eee-8b0e-11979e7852f4"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A major of FPT University",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 7, 9, 0, 14, 29, 625, DateTimeKind.Local).AddTicks(7652),
                            Name = "Information Systems"
                        },
                        new
                        {
                            Id = new Guid("1e0bbbd2-31cb-4f2d-973d-2e09a2224736"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A major of FPT University",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 7, 9, 0, 14, 29, 625, DateTimeKind.Local).AddTicks(7654),
                            Name = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = new Guid("94642f28-dc5d-4e9f-a0e2-d92e19eae1a4"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A major of FPT University",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 7, 9, 0, 14, 29, 625, DateTimeKind.Local).AddTicks(7656),
                            Name = "Information Security"
                        },
                        new
                        {
                            Id = new Guid("ead26ff9-4dc1-4089-8e0e-396a561061f9"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A major of FPT University",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 7, 9, 0, 14, 29, 625, DateTimeKind.Local).AddTicks(7658),
                            Name = "Digital Art Design"
                        },
                        new
                        {
                            Id = new Guid("8dad246f-7f30-4455-8b39-e74186c5a1fd"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A major of FPT University",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 7, 9, 0, 14, 29, 625, DateTimeKind.Local).AddTicks(7660),
                            Name = "Digital Marketing"
                        },
                        new
                        {
                            Id = new Guid("6b226e1d-d2f0-425d-8127-b3cee5c20f4f"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A major of FPT University",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 7, 9, 0, 14, 29, 625, DateTimeKind.Local).AddTicks(7662),
                            Name = "International Business"
                        },
                        new
                        {
                            Id = new Guid("503810ee-1850-4438-8e2b-3331fc1e7c36"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A major of FPT University",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 7, 9, 0, 14, 29, 625, DateTimeKind.Local).AddTicks(7664),
                            Name = "Hotel Management"
                        },
                        new
                        {
                            Id = new Guid("ce5e76f1-b49f-4546-a977-aac6de447b68"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A major of FPT University",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 7, 9, 0, 14, 29, 625, DateTimeKind.Local).AddTicks(7666),
                            Name = "Multimedia Communication"
                        },
                        new
                        {
                            Id = new Guid("d60261fb-ddaf-4917-bc71-2cc0d00c56de"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A major of FPT University",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 7, 9, 0, 14, 29, 625, DateTimeKind.Local).AddTicks(7670),
                            Name = "Finance"
                        },
                        new
                        {
                            Id = new Guid("ec1bc706-430e-4d6f-9105-0172451a1644"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A major of FPT University",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 7, 9, 0, 14, 29, 625, DateTimeKind.Local).AddTicks(7672),
                            Name = "Tourism Services Management"
                        },
                        new
                        {
                            Id = new Guid("5c75f924-7188-42ea-919e-bba5aaa7c22d"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A major of FPT University",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 7, 9, 0, 14, 29, 625, DateTimeKind.Local).AddTicks(7674),
                            Name = "English Language"
                        },
                        new
                        {
                            Id = new Guid("aeb339c9-3f83-495c-ac50-28af4913a990"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A major of FPT University",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 7, 9, 0, 14, 29, 625, DateTimeKind.Local).AddTicks(7676),
                            Name = "Chinese Language"
                        },
                        new
                        {
                            Id = new Guid("a81aa840-0c66-4af2-91dc-0aee704af57e"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A major of FPT University",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 7, 9, 0, 14, 29, 625, DateTimeKind.Local).AddTicks(7678),
                            Name = "Japanese Language"
                        },
                        new
                        {
                            Id = new Guid("55d25a7d-b8bc-4c90-99d8-2aa586d44055"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A major of FPT University",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 7, 9, 0, 14, 29, 625, DateTimeKind.Local).AddTicks(7680),
                            Name = "Korean Language"
                        },
                        new
                        {
                            Id = new Guid("946041da-5da2-4e29-ba3d-f348fbff4eca"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A major of FPT University",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 7, 9, 0, 14, 29, 625, DateTimeKind.Local).AddTicks(7682),
                            Name = "Automotive Digital Technology"
                        },
                        new
                        {
                            Id = new Guid("e75cb784-b305-4d1f-9209-b9e1e92e74ab"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A major of FPT University",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 7, 9, 0, 14, 29, 625, DateTimeKind.Local).AddTicks(7684),
                            Name = "Logistics"
                        },
                        new
                        {
                            Id = new Guid("2657b60b-0763-41af-bb26-ae6aa5113153"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A major of FPT University",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 7, 9, 0, 14, 29, 625, DateTimeKind.Local).AddTicks(7688),
                            Name = "Public Relations"
                        });
                });

            modelBuilder.Entity("BusinessObjects.Models.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.ToTable("tblNotifications");
                });

            modelBuilder.Entity("BusinessObjects.Models.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreaterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreaterId");

                    b.HasIndex("TopicId");

                    b.ToTable("tblPosts");
                });

            modelBuilder.Entity("BusinessObjects.Models.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Banner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<Guid>("MajorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MajorId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("tblProfiles");
                });

            modelBuilder.Entity("BusinessObjects.Models.Entities.RecentPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("tblRecentPosts");
                });

            modelBuilder.Entity("BusinessObjects.Models.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreaterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsRejected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponseContent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreaterId");

                    b.ToTable("tblReports");
                });

            modelBuilder.Entity("BusinessObjects.Models.Entities.SavedPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("tblSavedPosts");
                });

            modelBuilder.Entity("BusinessObjects.Models.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("NeedReview")
                        .HasColumnType("bit");

                    b.Property<string>("Panner")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tblTopics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a5e15215-85ba-4a56-b13c-4aec167c2d5b"),
                            Avatar = "https://firebasestorage.googleapis.com/v0/b/fir-6ea1c.appspot.com/o/images%2Fpost8242222e-2b8f-4a16-b281-e7f5ada75bc0?alt=media&token=2ebdbdf5-7cc1-4e60-a59e-9adbcd563f19",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Elementary Japanese 2",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 7, 9, 0, 14, 29, 625, DateTimeKind.Local).AddTicks(7508),
                            Name = "JPD123",
                            NeedReview = false,
                            Panner = "https://firebasestorage.googleapis.com/v0/b/fir-6ea1c.appspot.com/o/images%2Fpost8242222e-2b8f-4a16-b281-e7f5ada75bc0?alt=media&token=2ebdbdf5-7cc1-4e60-a59e-9adbcd563f19"
                        },
                        new
                        {
                            Id = new Guid("86a20668-e557-45d2-ae3f-d7401a8c6fcc"),
                            Avatar = "https://firebasestorage.googleapis.com/v0/b/fir-6ea1c.appspot.com/o/images%2Fpost8242222e-2b8f-4a16-b281-e7f5ada75bc0?alt=media&token=2ebdbdf5-7cc1-4e60-a59e-9adbcd563f19",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Software development project",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 7, 9, 0, 14, 29, 625, DateTimeKind.Local).AddTicks(7530),
                            Name = "SWP391",
                            NeedReview = false,
                            Panner = "https://firebasestorage.googleapis.com/v0/b/fir-6ea1c.appspot.com/o/images%2Fpost8242222e-2b8f-4a16-b281-e7f5ada75bc0?alt=media&token=2ebdbdf5-7cc1-4e60-a59e-9adbcd563f19"
                        },
                        new
                        {
                            Id = new Guid("0baeb57a-ddba-4741-98e6-bec47f53abc0"),
                            Avatar = "https://firebasestorage.googleapis.com/v0/b/fir-6ea1c.appspot.com/o/images%2Fpost8242222e-2b8f-4a16-b281-e7f5ada75bc0?alt=media&token=2ebdbdf5-7cc1-4e60-a59e-9adbcd563f19",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Object-Oriented Programming",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 7, 9, 0, 14, 29, 625, DateTimeKind.Local).AddTicks(7533),
                            Name = "PRO192",
                            NeedReview = false,
                            Panner = "https://firebasestorage.googleapis.com/v0/b/fir-6ea1c.appspot.com/o/images%2Fpost8242222e-2b8f-4a16-b281-e7f5ada75bc0?alt=media&token=2ebdbdf5-7cc1-4e60-a59e-9adbcd563f19"
                        },
                        new
                        {
                            Id = new Guid("5fccffd1-1576-4aea-83c1-f2a4848d370d"),
                            Avatar = "https://firebasestorage.googleapis.com/v0/b/fir-6ea1c.appspot.com/o/images%2Fpost8242222e-2b8f-4a16-b281-e7f5ada75bc0?alt=media&token=2ebdbdf5-7cc1-4e60-a59e-9adbcd563f19",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Software Testing",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 7, 9, 0, 14, 29, 625, DateTimeKind.Local).AddTicks(7536),
                            Name = "SWT301",
                            NeedReview = false,
                            Panner = "https://firebasestorage.googleapis.com/v0/b/fir-6ea1c.appspot.com/o/images%2Fpost8242222e-2b8f-4a16-b281-e7f5ada75bc0?alt=media&token=2ebdbdf5-7cc1-4e60-a59e-9adbcd563f19"
                        },
                        new
                        {
                            Id = new Guid("77f11fe6-6099-4a31-bbf4-afabe0e7edc2"),
                            Avatar = "https://firebasestorage.googleapis.com/v0/b/fir-6ea1c.appspot.com/o/images%2Fpost8242222e-2b8f-4a16-b281-e7f5ada75bc0?alt=media&token=2ebdbdf5-7cc1-4e60-a59e-9adbcd563f19",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Introduction to Software Engineering",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 7, 9, 0, 14, 29, 625, DateTimeKind.Local).AddTicks(7555),
                            Name = "SWE201c",
                            NeedReview = false,
                            Panner = "https://firebasestorage.googleapis.com/v0/b/fir-6ea1c.appspot.com/o/images%2Fpost8242222e-2b8f-4a16-b281-e7f5ada75bc0?alt=media&token=2ebdbdf5-7cc1-4e60-a59e-9adbcd563f19"
                        },
                        new
                        {
                            Id = new Guid("90d4a66a-b10c-454f-a67f-f759e3c0b22b"),
                            Avatar = "https://firebasestorage.googleapis.com/v0/b/fir-6ea1c.appspot.com/o/images%2Fpost8242222e-2b8f-4a16-b281-e7f5ada75bc0?alt=media&token=2ebdbdf5-7cc1-4e60-a59e-9adbcd563f19",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Statistics and Probability",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 7, 9, 0, 14, 29, 625, DateTimeKind.Local).AddTicks(7559),
                            Name = "MAS291",
                            NeedReview = false,
                            Panner = "https://firebasestorage.googleapis.com/v0/b/fir-6ea1c.appspot.com/o/images%2Fpost8242222e-2b8f-4a16-b281-e7f5ada75bc0?alt=media&token=2ebdbdf5-7cc1-4e60-a59e-9adbcd563f19"
                        },
                        new
                        {
                            Id = new Guid("d4e565a9-e789-4da2-97c2-e1c89d60a7a4"),
                            Avatar = "https://firebasestorage.googleapis.com/v0/b/fir-6ea1c.appspot.com/o/images%2Fpost8242222e-2b8f-4a16-b281-e7f5ada75bc0?alt=media&token=2ebdbdf5-7cc1-4e60-a59e-9adbcd563f19",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Elementary Japanese 1",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 7, 9, 0, 14, 29, 625, DateTimeKind.Local).AddTicks(7562),
                            Name = "JPD113",
                            NeedReview = false,
                            Panner = "https://firebasestorage.googleapis.com/v0/b/fir-6ea1c.appspot.com/o/images%2Fpost8242222e-2b8f-4a16-b281-e7f5ada75bc0?alt=media&token=2ebdbdf5-7cc1-4e60-a59e-9adbcd563f19"
                        },
                        new
                        {
                            Id = new Guid("bb059ee6-0bb8-4626-9f11-1d8accd1ced1"),
                            Avatar = "https://firebasestorage.googleapis.com/v0/b/fir-6ea1c.appspot.com/o/images%2Fpost8242222e-2b8f-4a16-b281-e7f5ada75bc0?alt=media&token=2ebdbdf5-7cc1-4e60-a59e-9adbcd563f19",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Java web Application",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 7, 9, 0, 14, 29, 625, DateTimeKind.Local).AddTicks(7617),
                            Name = "PRJ301",
                            NeedReview = false,
                            Panner = "https://firebasestorage.googleapis.com/v0/b/fir-6ea1c.appspot.com/o/images%2Fpost8242222e-2b8f-4a16-b281-e7f5ada75bc0?alt=media&token=2ebdbdf5-7cc1-4e60-a59e-9adbcd563f19"
                        },
                        new
                        {
                            Id = new Guid("508138da-3585-4e38-8b3d-184fba2e17d3"),
                            Avatar = "https://firebasestorage.googleapis.com/v0/b/fir-6ea1c.appspot.com/o/images%2Fpost8242222e-2b8f-4a16-b281-e7f5ada75bc0?alt=media&token=2ebdbdf5-7cc1-4e60-a59e-9adbcd563f19",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Internet of Things",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 7, 9, 0, 14, 29, 625, DateTimeKind.Local).AddTicks(7620),
                            Name = "IOT102",
                            NeedReview = false,
                            Panner = "https://firebasestorage.googleapis.com/v0/b/fir-6ea1c.appspot.com/o/images%2Fpost8242222e-2b8f-4a16-b281-e7f5ada75bc0?alt=media&token=2ebdbdf5-7cc1-4e60-a59e-9adbcd563f19"
                        },
                        new
                        {
                            Id = new Guid("06ff2454-f4d7-4ad2-b28a-6496467f5ac9"),
                            Avatar = "https://firebasestorage.googleapis.com/v0/b/fir-6ea1c.appspot.com/o/images%2Fpost8242222e-2b8f-4a16-b281-e7f5ada75bc0?alt=media&token=2ebdbdf5-7cc1-4e60-a59e-9adbcd563f19",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Programming Fundamentals",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 7, 9, 0, 14, 29, 625, DateTimeKind.Local).AddTicks(7623),
                            Name = "PRF192",
                            NeedReview = false,
                            Panner = "https://firebasestorage.googleapis.com/v0/b/fir-6ea1c.appspot.com/o/images%2Fpost8242222e-2b8f-4a16-b281-e7f5ada75bc0?alt=media&token=2ebdbdf5-7cc1-4e60-a59e-9adbcd563f19"
                        },
                        new
                        {
                            Id = new Guid("d6d05578-aa0a-4056-96b5-c19e28526109"),
                            Avatar = "https://firebasestorage.googleapis.com/v0/b/fir-6ea1c.appspot.com/o/images%2Fpost8242222e-2b8f-4a16-b281-e7f5ada75bc0?alt=media&token=2ebdbdf5-7cc1-4e60-a59e-9adbcd563f19",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Basis Cross-Platform Application Programming With .NET",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2025, 7, 9, 0, 14, 29, 625, DateTimeKind.Local).AddTicks(7627),
                            Name = "PRN212",
                            NeedReview = false,
                            Panner = "https://firebasestorage.googleapis.com/v0/b/fir-6ea1c.appspot.com/o/images%2Fpost8242222e-2b8f-4a16-b281-e7f5ada75bc0?alt=media&token=2ebdbdf5-7cc1-4e60-a59e-9adbcd563f19"
                        });
                });

            modelBuilder.Entity("BusinessObjects.Models.Entities.TopicBan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BannedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.HasIndex("UserId");

                    b.ToTable("tblTopicBans");
                });

            modelBuilder.Entity("BusinessObjects.Models.Entities.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUp")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VoterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("VoterId");

                    b.ToTable("tblVotes");
                });

            modelBuilder.Entity("tblMajorTopics", b =>
                {
                    b.Property<Guid>("MajorsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TopicsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MajorsId", "TopicsId");

                    b.HasIndex("TopicsId");

                    b.ToTable("tblMajorTopics");

                    b.HasData(
                        new
                        {
                            MajorsId = new Guid("058006cb-ea6e-4b78-a9cc-f41aed7b971c"),
                            TopicsId = new Guid("5fccffd1-1576-4aea-83c1-f2a4848d370d")
                        },
                        new
                        {
                            MajorsId = new Guid("058006cb-ea6e-4b78-a9cc-f41aed7b971c"),
                            TopicsId = new Guid("77f11fe6-6099-4a31-bbf4-afabe0e7edc2")
                        },
                        new
                        {
                            MajorsId = new Guid("058006cb-ea6e-4b78-a9cc-f41aed7b971c"),
                            TopicsId = new Guid("bb059ee6-0bb8-4626-9f11-1d8accd1ced1")
                        },
                        new
                        {
                            MajorsId = new Guid("058006cb-ea6e-4b78-a9cc-f41aed7b971c"),
                            TopicsId = new Guid("0baeb57a-ddba-4741-98e6-bec47f53abc0")
                        },
                        new
                        {
                            MajorsId = new Guid("a81aa840-0c66-4af2-91dc-0aee704af57e"),
                            TopicsId = new Guid("a5e15215-85ba-4a56-b13c-4aec167c2d5b")
                        },
                        new
                        {
                            MajorsId = new Guid("a81aa840-0c66-4af2-91dc-0aee704af57e"),
                            TopicsId = new Guid("d4e565a9-e789-4da2-97c2-e1c89d60a7a4")
                        },
                        new
                        {
                            MajorsId = new Guid("d60261fb-ddaf-4917-bc71-2cc0d00c56de"),
                            TopicsId = new Guid("90d4a66a-b10c-454f-a67f-f759e3c0b22b")
                        },
                        new
                        {
                            MajorsId = new Guid("c0a29af4-b397-4eee-8b0e-11979e7852f4"),
                            TopicsId = new Guid("508138da-3585-4e38-8b3d-184fba2e17d3")
                        });
                });

            modelBuilder.Entity("tblModerators", b =>
                {
                    b.Property<string>("ModeratedByUsersId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("ModeratedTopicsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ModeratedByUsersId", "ModeratedTopicsId");

                    b.HasIndex("ModeratedTopicsId");

                    b.ToTable("tblModerators");
                });

            modelBuilder.Entity("tblTopicFeeds", b =>
                {
                    b.Property<Guid>("FeedsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TopicsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FeedsId", "TopicsId");

                    b.HasIndex("TopicsId");

                    b.ToTable("tblTopicFeeds");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BusinessObjects.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BusinessObjects.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObjects.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BusinessObjects.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessObjects.Models.Entities.Attachment", b =>
                {
                    b.HasOne("BusinessObjects.Models.Entities.Post", "Post")
                        .WithMany("Attachments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("BusinessObjects.Models.Entities.Comment", b =>
                {
                    b.HasOne("BusinessObjects.Models.Entities.Attachment", "Attachment")
                        .WithMany("Comments")
                        .HasForeignKey("AttachmentId");

                    b.HasOne("BusinessObjects.Models.Entities.ApplicationUser", "Creater")
                        .WithMany("Comments")
                        .HasForeignKey("CreaterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BusinessObjects.Models.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObjects.Models.Entities.Comment", "ReplyTo")
                        .WithMany("Replies")
                        .HasForeignKey("ReplyToId");

                    b.Navigation("Attachment");

                    b.Navigation("Creater");

                    b.Navigation("Post");

                    b.Navigation("ReplyTo");
                });

            modelBuilder.Entity("BusinessObjects.Models.Entities.Feed", b =>
                {
                    b.HasOne("BusinessObjects.Models.Entities.ApplicationUser", "Creater")
                        .WithMany("Feeds")
                        .HasForeignKey("CreaterId");

                    b.Navigation("Creater");
                });

            modelBuilder.Entity("BusinessObjects.Models.Entities.Notification", b =>
                {
                    b.HasOne("BusinessObjects.Models.Entities.ApplicationUser", "Receiver")
                        .WithMany("Notifications")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("BusinessObjects.Models.Entities.Post", b =>
                {
                    b.HasOne("BusinessObjects.Models.Entities.ApplicationUser", "Creater")
                        .WithMany("CreatedPosts")
                        .HasForeignKey("CreaterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BusinessObjects.Models.Entities.Topic", "Topic")
                        .WithMany("Posts")
                        .HasForeignKey("TopicId");

                    b.Navigation("Creater");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("BusinessObjects.Models.Entities.Profile", b =>
                {
                    b.HasOne("BusinessObjects.Models.Entities.Major", "Major")
                        .WithMany("Profiles")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObjects.Models.Entities.ApplicationUser", "User")
                        .WithOne("Profile")
                        .HasForeignKey("BusinessObjects.Models.Entities.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObjects.Models.Entities.RecentPost", b =>
                {
                    b.HasOne("BusinessObjects.Models.Entities.Post", "Post")
                        .WithMany("RecentViews")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObjects.Models.Entities.ApplicationUser", "User")
                        .WithMany("RecentPosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObjects.Models.Entities.Report", b =>
                {
                    b.HasOne("BusinessObjects.Models.Entities.ApplicationUser", "Creater")
                        .WithMany("Reports")
                        .HasForeignKey("CreaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creater");
                });

            modelBuilder.Entity("BusinessObjects.Models.Entities.SavedPost", b =>
                {
                    b.HasOne("BusinessObjects.Models.Entities.Post", "Post")
                        .WithMany("SavedByUsers")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObjects.Models.Entities.ApplicationUser", "User")
                        .WithMany("SavedPosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObjects.Models.Entities.TopicBan", b =>
                {
                    b.HasOne("BusinessObjects.Models.Entities.Topic", "Topic")
                        .WithMany("BannedUser")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObjects.Models.Entities.ApplicationUser", "User")
                        .WithMany("BannedByTopics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObjects.Models.Entities.Vote", b =>
                {
                    b.HasOne("BusinessObjects.Models.Entities.Comment", "Comment")
                        .WithMany("Votes")
                        .HasForeignKey("CommentId");

                    b.HasOne("BusinessObjects.Models.Entities.Post", "Post")
                        .WithMany("Votes")
                        .HasForeignKey("PostId");

                    b.HasOne("BusinessObjects.Models.Entities.ApplicationUser", "Voter")
                        .WithMany("Votes")
                        .HasForeignKey("VoterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Post");

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("tblMajorTopics", b =>
                {
                    b.HasOne("BusinessObjects.Models.Entities.Major", null)
                        .WithMany()
                        .HasForeignKey("MajorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObjects.Models.Entities.Topic", null)
                        .WithMany()
                        .HasForeignKey("TopicsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("tblModerators", b =>
                {
                    b.HasOne("BusinessObjects.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ModeratedByUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObjects.Models.Entities.Topic", null)
                        .WithMany()
                        .HasForeignKey("ModeratedTopicsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("tblTopicFeeds", b =>
                {
                    b.HasOne("BusinessObjects.Models.Entities.Feed", null)
                        .WithMany()
                        .HasForeignKey("FeedsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObjects.Models.Entities.Topic", null)
                        .WithMany()
                        .HasForeignKey("TopicsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessObjects.Models.Entities.ApplicationUser", b =>
                {
                    b.Navigation("BannedByTopics");

                    b.Navigation("Comments");

                    b.Navigation("CreatedPosts");

                    b.Navigation("Feeds");

                    b.Navigation("Notifications");

                    b.Navigation("Profile");

                    b.Navigation("RecentPosts");

                    b.Navigation("Reports");

                    b.Navigation("SavedPosts");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("BusinessObjects.Models.Entities.Attachment", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("BusinessObjects.Models.Entities.Comment", b =>
                {
                    b.Navigation("Replies");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("BusinessObjects.Models.Entities.Major", b =>
                {
                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("BusinessObjects.Models.Entities.Post", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Comments");

                    b.Navigation("RecentViews");

                    b.Navigation("SavedByUsers");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("BusinessObjects.Models.Entities.Topic", b =>
                {
                    b.Navigation("BannedUser");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
